FROM cgr.dev/samcorp/python:3.13-dev@sha256:ce1bfef0bed04b1e2c2b4c81a203a2eb710b111f9c8b42a80eebb8bb21fde02e

WORKDIR /app

USER root

COPY requirements.txt .

RUN --mount=type=secret,id=netrc,target=/root/.netrc \
    uv pip install --system --no-cache-dir \
      --index-strategy unsafe-best-match \
      --index-url "https://libraries.cgr.dev/python-remediated/simple" \
      --extra-index-url "https://libraries.cgr.dev/python/simple" \
      --extra-index-url "https://pypi.org/simple" \
      -r requirements.txt

COPY . .

EXPOSE 5000

USER nonroot

ENTRYPOINT ["python", "app.py"]
