FROM cgr.dev/samcorp/python:3.13-dev@sha256:ec0bcde48d788bfbe985f63423a1e006c073255b4701893f4330e5db0931e686

WORKDIR /app

USER root

# Install uv 
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:$PATH"

COPY requirements.txt .
# Delete any pre-existing cache to ensure dependencies are pulled from the Chainguard repo
RUN rm -rf ~/.cache/pip

# Create virtual environment
RUN uv venv /app/venv
ENV PATH="/app/venv/bin:$PATH"

ENV UV_INDEX_URL="https://libraries.cgr.dev/python-remediated/simple"
ENV UV_EXTRA_INDEX_URL="https://libraries.cgr.dev/python/simple https://pypi.org/simple"

RUN --mount=type=secret,id=netrc,target=/root/.netrc \
    uv pip install --no-cache -r requirements.txt

COPY . .

EXPOSE 5000

ENTRYPOINT ["python", "app.py"]
