FROM cgr.dev/samcorp/python:3.13-dev@sha256:2c999d0cf62e451cb29f29311a2b3a8ce16a5cacb9d0374c9897e79d928e3da0

WORKDIR /app

USER root

COPY requirements.txt .

RUN --mount=type=secret,id=netrc,target=/root/.netrc \
    uv pip install --system --no-cache-dir \
      --index-strategy unsafe-best-match \
      --index-url "https://libraries.cgr.dev/python-remediated/simple" \
      --extra-index-url "https://libraries.cgr.dev/python/simple" \
      --extra-index-url "https://pypi.org/simple" \
      -r requirements.txt

COPY . .

EXPOSE 5000

USER nonroot

ENTRYPOINT ["python", "app.py"]
