FROM cgr.dev/samcorp/python:3.13-dev@sha256:80cb4313b966b4483a76e46753a771413d9134a7fed4963b4248da07ab34eaee

WORKDIR /app

USER root

COPY requirements.txt .

RUN --mount=type=secret,id=netrc,target=/root/.netrc \
    pip install --no-cache-dir \
      --index-url "https://libraries.cgr.dev/python-remediated/simple" \
      --extra-index-url "https://libraries.cgr.dev/python/simple" \
      --extra-index-url "https://pypi.org/simple" \
      -r requirements.txt

COPY . .

EXPOSE 5000

USER nonroot

ENTRYPOINT ["python", "app.py"]
