name: Pull request workflow

on:
  pull_request

jobs:
  build-and-push-image:
    uses: ./.github/workflows/build-and-push.yml
    with:
      IMAGE_TAG: pr-${{ github.event.number }}
    secrets:
      CGR_USERNAME: ${{ secrets.CGR_USERNAME }}
      CGR_PASSWORD: ${{ secrets.CGR_PASSWORD }}
      CHAINCTL_IDENTITY: ${{ secrets.CHAINCTL_IDENTITY }}

  sec:
    needs: build-and-push-image
    uses: ./.github/workflows/sec.yml
    with:
      IMAGE_TAG: pr-${{ github.event.number }}