name: Security workflow
on:
  workflow_call:
    secrets:
      DOCKERHUB_TOKEN:
        required: true
    inputs:
      IMAGE_TAG:
        required: true
        type: string

env:
  REGISTRY: sammorriscg
  FRONTEND_IMAGE_NAME: cg-e2e-frontend
  BACKEND_IMAGE_NAME: cg-e2e-backend
  USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
  PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  grype:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}
      
      - name: Scan image (Frontend)
        id: frontend
        uses: anchore/scan-action@v6
        with:
          image: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ inputs.IMAGE_TAG }}
          fail-build: false
          output-format: sarif
          output-file: frontend-scan.sarif

      - name: Scan image (Backend)
        id: backend-grype
        uses: anchore/scan-action@v6
        with:
          image: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:${{ inputs.IMAGE_TAG }}
          fail-build: false
          output-format: sarif
          output-file: backend-scan.sarif

      - name: Upload SARIF files
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: |
            frontend-scan.sarif
            backend-scan.sarif

      - name: Inspect action SARIF report
        run: cat ${{ steps.scan.outputs.sarif }}